-- =====================================================================
-- SOURCE           = LIVE OBJECT_DEFINITION
-- AUDITED_AT       = 2026-10-06
-- LEGACY_EXECUTION_SAFE = YES (verificado en Testcontainers)
-- =====================================================================
-- Copia textual fiel de CALE_IMMEX.dbo.CARGACONSTANCIAS (READ-ONLY).
-- Prohibido idealizar columnas, tipos, nombres, ordering, MAX()+1 ni los
-- side effects globales (DELETE FROM ERRORCARGA, UPDATE SALIDAS ... 'CT',
-- DELETE FROM GENERADORES).
USE [CALE_IMMEX];
GO
CREATE PROCEDURE [dbo].[CARGACONSTANCIAS]
AS
BEGIN

-- BORRO LOS ERRORES
DELETE FROM ERRORCARGA

DECLARE
    @ADUANA VARCHAR(50) ,
    @PATENTE VARCHAR(50) ,
    @NUMEROPEDIMENTO VARCHAR(50) ,
    @CLAVEPEDIMENTO VARCHAR(50) ,
    @TIPOOPERACION INT ,
    @TIPOPEDIMENTO INT ,
    @TC FLOAT ,
    @FECHAPAGO DATETIME ,
    @CLAVECP VARCHAR(50) ,
    @NOMBRECP VARCHAR(50) ,
    @IGIE FLOAT ,
    @IVA FLOAT ,
    @DTA FLOAT ,
    @PREV FLOAT ,
    @SEC INT ,
    @CLAVE VARCHAR(50) ,
    @DESCRIPCION VARCHAR(250) ,
    @FRACCION VARCHAR(50) ,
    @CANTIDADCOMERCIAL FLOAT ,
    @UNIDADCOMERCIAL VARCHAR(50) ,
    @CANTIDADTARIFA FLOAT ,
    @UNIDADTARIFA VARCHAR(50) ,
    @PAISOD VARCHAR(50) ,
    @PAISCV VARCHAR(50) ,
    @VALORDOLARES FLOAT ,
    @VALORCOMERCIAL FLOAT ,
    @VALORADUANAL FLOAT ,
    @VALORME FLOAT ,
    @FACTURA VARCHAR(50) ,
    @FECHAFACTURA DATETIME ,
    @PEDIMENTOORIGINAL VARCHAR(50) ,
    @DESCARGADIRIGIDA VARCHAR(50) ,
    @CARGAKEY BIGINT,
    @TADUANA INT,
    @TPATENTE INT,
    @TCLAVEPEDIMENTO INT,
    @TTIPOOPERACION INT,
    @TTIPOPEDIMENTO INT,
    @TTC INT,
    @TFECHAPAGO INT,
    @MATERIALKEY INT,
    @TPEDIMENTOORIGINAL INT





-- VERIFICO QUE TENGA UNA ADUANA VALIDA
--INSERT INTO DBO.ERRORCARGA
--(CARGAKEY,ERROR)
--SELECT CONSTANCIAKEY,'LONGITUD DE LA ADUANA ERRONEA' FROM DBO.CONSTANCIATRANSF
--WHERE
--LEN(ADUANA) <> 3


INSERT INTO DBO.ERRORCARGA
(CARGAKEY,ERROR)
SELECT CONSTANCIAKEY,'LONGITUD ERRONEA DE LA CLAVE DE PRODUCTO'
FROM DBO.CONSTANCIATRANSF
WHERE
LEN(ISNULL(NOPARTE,'')) <= 1

INSERT INTO DBO.ERRORCARGA
(CARGAKEY,ERROR)
SELECT CONSTANCIAKEY,'LONGITUD ERRONEA DE LA DESCRIPCION' FROM DBO.CONSTANCIATRANSF
WHERE
LEN(DESCRIPCION) <= 1 and
NOPARTE not in
(select CVE_PRODUCTO from dbo.productos)


INSERT INTO DBO.ERRORCARGA
(CARGAKEY,ERROR)
SELECT CONSTANCIAKEY,'LONGITUD ERRONEA DEL CLIENTE O PROVEEDOR' FROM DBO.CONSTANCIATRANSF
WHERE
LEN(PROV) <= 1




-- REVISA LOS NUMEROS DE PARTE Y LOS CODIGOS DE PRODUCTO.

DECLARE @INSERTA AS VARCHAR(2)

SELECT @INSERTA = ISNULL((SELECT VALUE FROM dbo.settings WHERE dbo.settings.settings = 'I_CARGAPRODUCTOSCONST'),'SI')


IF @INSERTA = 'SI'
BEGIN

 SELECT @MATERIALKEY = (SELECT ISNULL(MAX(PRODUCTOKEY),0) + 1 FROM PRODUCTOS)

 INSERT INTO DBO.PRODUCTOS
(PRODUCTOKEY,CVE_PRODUCTO,NOMBRE,UNIDAD,FRACCION)

SELECT ROW_NUMBER() OVER(ORDER BY CLAVE) + @MATERIALKEY,
CLAVE,DESCRIPCION,'PZA','0000000'
 FROM
(
SELECT DISTINCT NOPARTE CLAVE,
(SELECT TOP 1 DESCRIPCION FROM DBO.CONSTANCIATRANSF AS XX WHERE XX.NOPARTE = YY.NOPARTE) DESCRIPCION
 FROM DBO.CONSTANCIATRANSF YY
 WHERE
 NOPARTE NOT IN
 (SELECT CVE_PRODUCTO FROM DBO.PRODUCTOS)
 ) AS CLAVES

 WHERE ISNULL(DESCRIPCION,'') <> '' AND ISNULL(CLAVE,'') <> ''

END



-- GENERA ERROR DE LOS PRODUCTOS Y MATERIALES QUE NO ESTEN EN EL CATALOGO
-- Y QUE LA UNIDAD ES DIFERENTE

-- EL CODIGO NO ESTA EN EL CATALOGO

-- LA UNIDAD DE MEDIDA NO ESTA EN EL CATALOGO

INSERT INTO DBO.ERRORCARGA
(CARGAKEY,ERROR)

SELECT  CONSTANCIAKEY,'EL CODIGO DEL PRODUCTO NO EXISTE EN EL CATALOGO'
FROM DBO.CONSTANCIATRANSF IE
WHERE
IE.CONSTANCIAKEY NOT IN
(
SELECT X1.CONSTANCIAKEY FROM PRODUCTOS, DBO.CONSTANCIATRANSF X1
WHERE
PRODUCTOS.CVE_PRODUCTO = X1.NOPARTE
)





-- SELECCIONO LOS PEDIMENTOS QUE NO TIENEN ERROR

DECLARE @IPEDIMENTOKEY BIGINT,
        @PARTIDAKEY BIGINT,
        @SALIDAKEY BIGINT,
        @PSALIDAKEY BIGINT,
        @CLIENTEKEY BIGINT,
        @PROVEEDORKEY BIGINT


SELECT @IPEDIMENTOKEY = (SELECT ISNULL(MAX(IPEDIMENTOKEY),0) + 1 FROM IMPORTACIONES)
SELECT @PARTIDAKEY = (SELECT ISNULL(MAX(PARTIDAKEY),0) + 1 FROM PARTIDAS)
SELECT @SALIDAKEY = (SELECT ISNULL(MAX(SALIDAKEY),0) + 1 FROM SALIDAS)
SELECT @PSALIDAKEY = (SELECT ISNULL(MAX(PSALIDAKEY),0) + 1 FROM PSALIDAS)
SELECT @CLIENTEKEY = (SELECT ISNULL(MAX(CLIENTEKEY),0) + 1 FROM CLIENTES)
SELECT @PROVEEDORKEY = (SELECT ISNULL(MAX(PROVEEDORKEY),0) + 1 FROM PROVEEDORES)



-- INSERTO IMPORTACIONES

-- INSERTO SALIDAS

INSERT INTO SALIDAS
(SALIDAKEY,TIPO_OPERACION,ADUANA,AGENTE,DOCUMENTO,FECHA,CVE_PEDIMENTO,TC, DESCARGA,PEDIMENTOORIGINAL,
PAIS,ORIGEN,DTA, PREV,CVE_CLIENTE,FECHADESCARGA
)
SELECT ROW_NUMBER() OVER(ORDER BY FECHAPAGO) + @SALIDAKEY,
TIPOOPER,ADUANA,PATENTE,NUMEROPEDIMENTO,FECHAPAGO,CLAVEPEDIMENTO,TC , DESCARGA,PEDIMENTOORIGINAL,
'-',
'-',
0,
0,
(SELECT TOP 1 ISNULL(PROV,'-') FROM DBO.CONSTANCIATRANSF AS X1 WHERE X1.NUMERODEFOLIO = XX.NUMEROPEDIMENTO)
,FD
FROM
(
SELECT
DISTINCT 'CONST TRANSFERENCIA' TIPOOPER,'-' ADUANA,'-' PATENTE,NUMERODEFOLIO NUMEROPEDIMENTO,FECHACREACION
FECHAPAGO,'CT'CLAVEPEDIMENTO,1 TC,
'SI' DESCARGA,'' PEDIMENTOORIGINAL
,ISNULL(PERIODO,'') FD
FROM
DBO.CONSTANCIATRANSF
WHERE
NUMERODEFOLIO
 NOT IN
(SELECT NUMERODEFOLIO FROM DBO.CONSTANCIATRANSF T1 , DBO.ERRORCARGA T2
WHERE
T1.CONSTANCIAKEY = T2.CARGAKEY
)

) AS XX
WHERE NUMEROPEDIMENTO NOT IN
(SELECT DOCUMENTO FROM SALIDAS WHERE DOCUMENTO IS  NOT NULL)


-- INSERTO DETALLE DE SALIDAS


INSERT INTO PSALIDAS
(PSALIDAKEY,CLAVE,DESCRIPCION,FRACCION,CANTIDAD,UNIDAD,VAL_DOLARES,PAISD,CODPROVEEDOR,
CANTIDADT,UNIDADT,VAL_PESOS,FACTURA,FECHA,PARTIDA,SALIDALINK,
DESCARGADIRIGIDA,
BLOQUEADO,CORTE,ANEXO,pedimentoexportacionctm
)

SELECT ROW_NUMBER() OVER(ORDER BY SEC) + @PSALIDAKEY,
NOPARTE,(SELECT TOP 1 PRODUCTOS.NOMBRE FROM PRODUCTOS WHERE CVE_PRODUCTO = NOPARTE)
,(SELECT TOP 1 PRODUCTOS.FRACCION FROM PRODUCTOS WHERE CVE_PRODUCTO = NOPARTE),CANTIDAD,
(SELECT TOP 1 PRODUCTOS.UNIDAD FROM PRODUCTOS WHERE CVE_PRODUCTO = NOPARTE)
,val_dolares,'',ISNULL(PROV,'-') ,
CANTIDAD,
(SELECT TOP 1 PRODUCTOS.UNIDAD FROM PRODUCTOS WHERE CVE_PRODUCTO = NOPARTE)
,Val_Comercial,SUBSTRING(NUMERODEFOLIO,1,20),FECHACREACION,LIN,
(SELECT  TOP 1 SALIDAKEY FROM SALIDAS WHERE DOCUMENTO = DBO.CONSTANCIATRANSF.NUMERODEFOLIO),
--ADUANA + '-' +PEDIMENTO ,
null,
0,ISNULL(PERIODO,''),MER,PEDIMENTO
FROM
DBO.CONSTANCIATRANSF
WHERE
CONSTANCIAKEY NOT IN
(SELECT DISTINCT DBO.ERRORCARGA.CARGAKEY FROM DBO.ERRORCARGA)

AND
 DBO.CONSTANCIATRANSF.NUMERODEFOLIO IN
(SELECT DOCUMENTO FROM SALIDAS IM WHERE IM.SALIDAKEY >= @SALIDAKEY)


UPDATE SALIDAS
SET TIPO_OPERACION = 'CONST TRANSFERENCIA'
WHERE CVE_PEDIMENTO = 'CT'



-- CREO LOS DIRIGIDOS

DECLARE @DIRIGIDOKEY AS BIGINT

SELECT @DIRIGIDOKEY = (SELECT ISNULL(MAX(DIRIGIDOKEY),0) +  1 FROM DIRIGIDO)

INSERT INTO DIRIGIDO
(DIRIGIDOKEY,DOCUMENTO,CLAVE,INCORPORADO,DESPERDICIO,MERMA,SALIDAKEY, PSALIDAKEY)
SELECT
ROW_NUMBER() OVER(ORDER BY PSALIDAKEY) + @DIRIGIDOKEY ,
DESCARGADIRIGIDA,CLAVE,CANTIDAD,0,0,SALIDALINK,PSALIDAKEY

FROM
PSALIDAS
WHERE
DESCARGADIRIGIDA <> '' AND PSALIDAKEY NOT IN
(SELECT DISTINCT PSALIDAKEY FROM DIRIGIDO)




--- TERMINA DE CREAR LOS DIRIGIDOS

DELETE FROM GENERADORES



END
GO
