package com.jovycandy.anexo24.reports;

import org.junit.jupiter.api.*; import org.testcontainers.DockerClientFactory; import org.testcontainers.containers.MSSQLServerContainer; import java.nio.file.*; import java.sql.*; import java.math.BigDecimal; import static org.junit.jupiter.api.Assertions.*;
/** Verifica LEFT JOIN y paginación del SP versionado de descargas A31. */
class Anexo30DescargasSqlIT {
 static final MSSQLServerContainer<?> SQL=new MSSQLServerContainer<>("mcr.microsoft.com/mssql/server:2022-latest").acceptLicense(); static boolean ok;
 @BeforeAll static void start()throws Exception{ok=DockerClientFactory.instance().isDockerAvailable();Assumptions.assumeTrue(ok,"Docker no disponible localmente");SQL.start();try(Connection c=con("master");Statement s=c.createStatement()){s.execute("CREATE DATABASE CALE_IMMEX");}try(Connection c=con("CALE_IMMEX");Statement s=c.createStatement()){s.execute("CREATE TABLE dbo.A31_ENTRADAS(Entradaskey BIGINT IDENTITY PRIMARY KEY,Pedimentoarmado varchar(30),PEDIMENTOORIGINAL varchar(30),Fecha datetime,Clavepedimento varchar(5),Fracccion varchar(10),Valocomercial numeric(18,4),SALDO numeric(18,4),ESAF varchar(5),PARTIDA varchar(10))");s.execute("CREATE TABLE dbo.A31_DESCARGASF(A31_FRACCIONKEY BIGINT IDENTITY PRIMARY KEY,TIPO varchar(2),CLAVEPEDIMENTO varchar(5),EJERCICIO varchar(5),PERIODO varchar(5),FRACCION varchar(10),VALOR numeric(18,4),AF varchar(5),ARCHIVO varchar(50))");s.execute("CREATE TABLE dbo.A31_DESCARGAS(A31_DESCARGAKEY BIGINT IDENTITY PRIMARY KEY,ENTRADALINK BIGINT NULL,FRACCION varchar(10),VALORDESCARGADO numeric(18,4),A31_FRACCIONLINK BIGINT NULL)");apply(c);}}
 @AfterAll static void stop(){if(ok)SQL.stop();}
 @BeforeEach void data()throws Exception{try(Connection c=con("CALE_IMMEX");Statement s=c.createStatement()){s.execute("DELETE FROM dbo.A31_DESCARGAS;DELETE FROM dbo.A31_ENTRADAS;DELETE FROM dbo.A31_DESCARGASF");s.execute("INSERT dbo.A31_ENTRADAS(Pedimentoarmado,Fecha,Clavepedimento,Fracccion,Valocomercial,SALDO,ESAF,PARTIDA) VALUES('PED-1','2026-01-01','A1','84715002',100,90,'SI','1')");s.execute("INSERT dbo.A31_DESCARGASF(TIPO,CLAVEPEDIMENTO,EJERCICIO,PERIODO,FRACCION,VALOR,AF,ARCHIVO) VALUES('F4','A1','2026','01','84715002',100,'SI','a.txt')");s.execute("INSERT dbo.A31_DESCARGAS(ENTRADALINK,FRACCION,VALORDESCARGADO,A31_FRACCIONLINK) VALUES(1,'84715002',10.0000,1),(999,'98000000',123.4567,998),(NULL,'00000000',1.0000,NULL)");}}
 @Test void conservaDescargasHuerfanasConLeftJoin()throws Exception{try(Connection c=con("CALE_IMMEX");CallableStatement x=c.prepareCall("{call dbo.APP24_Q_ANEXO30_REVISION_DESCARGAS_LISTAR(?,?,?,?)}")){x.setString(1,"98000000");x.setInt(2,1);x.setInt(3,20);x.registerOutParameter(4,Types.BIGINT);x.execute();ResultSet r=x.getResultSet();assertTrue(r.next());assertNotNull(r.getObject("DESCARGA_KEY"));assertEquals("98000000",r.getString("FRACCION_DESCARGA"));assertEquals(new BigDecimal("123.4567"),r.getBigDecimal("VALOR_DESCARGADO"));assertNull(r.getObject("PEDIMENTO"));assertNull(r.getObject("ARCHIVO"));assertEquals(1,x.getLong(4));}}
 static Connection con(String db)throws Exception{return DriverManager.getConnection("jdbc:sqlserver://"+SQL.getHost()+":"+SQL.getMappedPort(1433)+";databaseName="+db+";encrypt=false;trustServerCertificate=true",SQL.getUsername(),SQL.getPassword());}
 static void apply(Connection c)throws Exception{Path p=Path.of("..","infra/sql/procedures/queries/APP24_Q_ANEXO30_REVISION_DESCARGAS_LISTAR.sql");if(!Files.exists(p))p=Path.of("infra/sql/procedures/queries/APP24_Q_ANEXO30_REVISION_DESCARGAS_LISTAR.sql");for(String b:Files.readString(p).split("(?im)^GO\s*$")){if(!b.isBlank())try(Statement s=c.createStatement()){s.execute(b);}}}
}
