USE ANEXO24_DEV;
GO

CREATE OR ALTER PROCEDURE app24.APP24_Q_PEDIMENTO_CARGA_POR_HASH
    @Hash VARCHAR(64),
    @Existe BIT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    SELECT @Existe = CASE WHEN EXISTS (SELECT 1 FROM app24.CargaPedimento WHERE hash = @Hash) THEN 1 ELSE 0 END;
END;
GO
