USE ANEXO24_DEV;
GO

CREATE OR ALTER PROCEDURE app24.APP24_Q_FACTURACION_CARGA_POR_HASH
    @Hash VARCHAR(64),
    @Existe BIT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    IF @Hash IS NULL OR LEN(@Hash) <> 64 THROW 51108, 'PARAMETRO_INVALIDO', 1;
    SET @Existe = CASE WHEN EXISTS (SELECT 1 FROM app24.CargaFacturacion WHERE hash = @Hash) THEN 1 ELSE 0 END;
END;
GO
