USE [CALE_IMMEX];
GO
CREATE OR ALTER PROCEDURE dbo.APP24_Q_ANEXO30_REVISION_COMPARATIVA_LISTAR
    @Filtro VARCHAR(60) = NULL,
    @Pagina INT = 1,
    @Tamano INT = 20,
    @Total BIGINT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    IF @Pagina < 1 OR @Tamano < 1 OR @Tamano > 100
        THROW 51000, 'La paginación no es válida.', 1;
    SET @Filtro = NULLIF(LTRIM(RTRIM(@Filtro)), '');
    SELECT @Total = COUNT_BIG(*)
    FROM dbo.A31_COMPARATIVADESCARGA c
    WHERE @Filtro IS NULL OR c.CLAVEPEDIMENTO LIKE '%' + @Filtro + '%'
       OR c.EJERCICIO LIKE '%' + @Filtro + '%' OR c.PERIODO LIKE '%' + @Filtro + '%'
       OR c.FRACCION LIKE '%' + @Filtro + '%';
    SELECT c.CLAVEPEDIMENTO AS CLAVE_PEDIMENTO, c.EJERCICIO, c.PERIODO, c.FRACCION,
           c.[VALOR A31] AS VALOR_A31, c.[VALOR A24] AS VALOR_A24, c.DIFERENCIA,
           c.IVA21TOTAL AS IVA21_TOTAL, c.IVA22TOTAL AS IVA22_TOTAL, c.VALORTOTAL AS VALOR_TOTAL,
           c.[IVA DESCARGADO A31] AS IVA_DESCARGADO_A31, c.[IVA DESCARGADO A24] AS IVA_DESCARGADO_A24
    FROM dbo.A31_COMPARATIVADESCARGA c
    WHERE @Filtro IS NULL OR c.CLAVEPEDIMENTO LIKE '%' + @Filtro + '%'
       OR c.EJERCICIO LIKE '%' + @Filtro + '%' OR c.PERIODO LIKE '%' + @Filtro + '%'
       OR c.FRACCION LIKE '%' + @Filtro + '%'
    ORDER BY TRY_CONVERT(INT, c.EJERCICIO) DESC, TRY_CONVERT(INT, c.PERIODO) DESC,
             c.CLAVEPEDIMENTO, c.FRACCION, c.[VALOR A31], c.[VALOR A24], c.DIFERENCIA,
             c.IVA21TOTAL, c.IVA22TOTAL, c.VALORTOTAL, c.[IVA DESCARGADO A31], c.[IVA DESCARGADO A24]
    OFFSET CONVERT(BIGINT, @Pagina - 1) * @Tamano ROWS FETCH NEXT @Tamano ROWS ONLY;
END;
GO
