-- Permisos mínimos posteriores a la creación de los SP de Facturación V2.
USE ANEXO24_DEV;
GO
GRANT EXECUTE ON OBJECT::app24.APP24_C_FACTURACION_CARGA_CREAR TO app24_runtime;
GRANT EXECUTE ON OBJECT::app24.APP24_Q_FACTURACION_CARGA_POR_HASH TO app24_runtime;
GRANT EXECUTE ON OBJECT::app24.APP24_Q_FACTURACION_PLANTILLA_ACTIVA TO app24_runtime;
GRANT EXECUTE ON OBJECT::app24.APP24_Q_FACTURACION_CARGA_OBTENER TO app24_runtime;
GO
