-- Fixture mínimo de CALE_IMMEX para el test de integración del command.
-- Sólo estructura necesaria para ejecutar el SP REAL; no replica lógica empresarial.
-- Las funciones dbo.FACTOR / dbo.VALIDUNIT son implementaciones de prueba con la
-- misma firma y el contrato mínimo que consume el command (no la lógica completa).

IF OBJECT_ID('dbo.IMPORTACIONES', 'U') IS NULL
CREATE TABLE dbo.IMPORTACIONES (
    IPEDIMENTOKEY NUMERIC(18,0) NOT NULL CONSTRAINT PK_Importaciones PRIMARY KEY,
    ADUANA VARCHAR(10) NULL, PATENTE VARCHAR(10) NULL, NUMERO_PED VARCHAR(20) NULL,
    FECHA DATETIME NULL, TIPOOPER VARCHAR(25) NULL, CVE_PEDIMENTO VARCHAR(5) NULL,
    TC FLOAT NULL, DESCARGA VARCHAR(2) NULL, PEDIMENTOORIGINAL VARCHAR(20) NULL,
    CVEPROVEEDOR VARCHAR(15) NULL, IVA FLOAT NULL, DTA FLOAT NULL, PREVALIDACION FLOAT NULL,
    CNT NUMERIC(18,4) NULL, ADVALOREM FLOAT NULL, MULTAS NUMERIC(18,4) NULL,
    RECARGOS NUMERIC(18,4) NULL, FECHA_AD DATETIME NULL, IVA_PRE NUMERIC(18,4) NULL);
GO

IF OBJECT_ID('dbo.PARTIDAS', 'U') IS NULL
CREATE TABLE dbo.PARTIDAS (
    PARTIDAKEY NUMERIC(18,0) NOT NULL CONSTRAINT PK_partidas PRIMARY KEY,
    CLAVE VARCHAR(50) NULL, DESCRIPCION VARCHAR(250) NULL, FRACCION VARCHAR(15) NULL,
    CANTIDAD NUMERIC(18,4) NULL, UNIDAD VARCHAR(10) NULL, VAL_ADUANAL NUMERIC(18,4) NULL,
    VAL_DOLARES NUMERIC(18,4) NULL, ORIGEN VARCHAR(50) NULL, SALDO NUMERIC(18,4) NULL,
    CATEGORIA CHAR(5) NULL, PROVEEDOR CHAR(15) NULL, CANTIDADT FLOAT NULL, UNIDADT CHAR(5) NULL,
    VAL_COMERCIAL FLOAT NULL, FACTURA CHAR(30) NULL, FECHAFACTURA DATETIME NULL, PARTIDA INT NULL,
    IMPORTACIONLINK NUMERIC(18,0) NULL, MONTOIGI FLOAT NULL, MONTOIVA FLOAT NULL,
    MONTOCCOMPEN FLOAT NULL, PAISVENDEDOR VARCHAR(50) NULL, LOTE VARCHAR(50) NULL,
    COMPLEMENTO1 VARCHAR(50) NULL, COMPLEMENTO2 VARCHAR(50) NULL, COMPLEMENTO3 VARCHAR(50) NULL,
    valorME NUMERIC(18,4) NULL, arancel FLOAT NULL, fpigi FLOAT NULL, fpiva FLOAT NULL,
    tasaiva FLOAT NULL, tipotasaigie VARCHAR(50) NULL, marca VARCHAR(50) NULL,
    modelo VARCHAR(50) NULL, serie VARCHAR(50) NULL, COVE VARCHAR(100) NULL, FME NUMERIC(18,4) NULL,
    FACINC NUMERIC(18,4) NULL, ESACTIVO VARCHAR(2) NULL, PESOBRUTO NUMERIC(18,4) NULL,
    INCOTERM VARCHAR(5) NULL, NICO VARCHAR(10) NULL);
GO

IF OBJECT_ID('dbo.SALIDAS', 'U') IS NULL
CREATE TABLE dbo.SALIDAS (
    SALIDAKEY NUMERIC(18,0) NOT NULL CONSTRAINT PK_salidas PRIMARY KEY,
    TIPO_OPERACION VARCHAR(50) NULL, ADUANA VARCHAR(10) NULL, AGENTE VARCHAR(10) NULL,
    DOCUMENTO VARCHAR(20) NULL, FECHA DATETIME NULL, CVE_PEDIMENTO VARCHAR(5) NULL, TC FLOAT NULL,
    DESCARGA VARCHAR(2) NULL, PEDIMENTOORIGINAL VARCHAR(20) NULL, PAIS VARCHAR(50) NULL,
    ORIGEN VARCHAR(50) NULL, DTA FLOAT NULL, PREV FLOAT NULL, CVE_CLIENTE VARCHAR(15) NULL,
    MULTAS NUMERIC(18,4) NULL, RECARGOS NUMERIC(18,4) NULL, IVA_PRE NUMERIC(18,4) NULL,
    TIPODESCARGA VARCHAR(20) NULL);
GO

IF OBJECT_ID('dbo.PSALIDAS', 'U') IS NULL
CREATE TABLE dbo.PSALIDAS (
    PSALIDAKEY NUMERIC(18,0) NOT NULL CONSTRAINT PK_psalidas PRIMARY KEY,
    CLAVE VARCHAR(50) NULL, DESCRIPCION VARCHAR(250) NULL, FRACCION VARCHAR(15) NULL,
    CANTIDAD NUMERIC(18,4) NULL, UNIDAD VARCHAR(10) NULL, VAL_DOLARES NUMERIC(18,4) NULL,
    PAISD VARCHAR(50) NULL, CODPROVEEDOR VARCHAR(50) NULL, CANTIDADT FLOAT NULL,
    UNIDADT VARCHAR(10) NULL, VAL_PESOS FLOAT NULL, FACTURA VARCHAR(30) NULL, FECHA DATETIME NULL,
    PARTIDA INT NULL, SALIDALINK NUMERIC(18,0) NULL, DESCARGADIRIGIDA VARCHAR(50) NULL,
    BLOQUEADO INT NULL, CORTE VARCHAR(50) NULL, marca VARCHAR(50) NULL, modelo VARCHAR(50) NULL,
    serie VARCHAR(50) NULL, ValorAduanaCR NUMERIC(18,4) NULL, fpiva FLOAT NULL,
    montoiva FLOAT NULL, paisc VARCHAR(50) NULL, ValorME NUMERIC(18,4) NULL,
    COVE VARCHAR(100) NULL, NICO VARCHAR(10) NULL);
GO

IF OBJECT_ID('dbo.DIRIGIDO', 'U') IS NULL
CREATE TABLE dbo.DIRIGIDO (
    DIRIGIDOKEY NUMERIC(18,0) NOT NULL CONSTRAINT PK_dirigido PRIMARY KEY,
    DOCUMENTO VARCHAR(50) NULL, CLAVE VARCHAR(50) NULL, INCORPORADO NUMERIC(18,4) NULL,
    DESPERDICIO NUMERIC(18,4) NULL, MERMA NUMERIC(18,4) NULL, SALIDAKEY NUMERIC(18,0) NULL,
    PSALIDAKEY NUMERIC(18,0) NULL);
GO

IF OBJECT_ID('dbo.MATERIAL', 'U') IS NULL
CREATE TABLE dbo.MATERIAL (
    MATERIALKEY NUMERIC(18,0) NOT NULL CONSTRAINT PK_material PRIMARY KEY,
    CLAVE VARCHAR(50) NULL, UNIDAD VARCHAR(10) NULL, DESCRIPCION VARCHAR(250) NULL);
GO

IF OBJECT_ID('dbo.PRODUCTOS', 'U') IS NULL
CREATE TABLE dbo.PRODUCTOS (
    PRODUCTOKEY NUMERIC(18,0) NOT NULL CONSTRAINT PK_productos PRIMARY KEY,
    CVE_PRODUCTO VARCHAR(50) NULL, UNIDAD VARCHAR(10) NULL);
GO

-- Funciones fixture: misma firma/contrato mínimo consumido por el command.
IF OBJECT_ID('dbo.VALIDUNIT', 'FN') IS NOT NULL DROP FUNCTION dbo.VALIDUNIT;
GO
CREATE FUNCTION dbo.VALIDUNIT(@unidad VARCHAR(50))
RETURNS VARCHAR(50)
AS
BEGIN
    RETURN CASE WHEN @unidad IS NULL OR LTRIM(RTRIM(@unidad)) = '' THEN 'SD' ELSE LTRIM(RTRIM(@unidad)) END;
END;
GO

IF OBJECT_ID('dbo.FACTOR', 'FN') IS NOT NULL DROP FUNCTION dbo.FACTOR;
GO
CREATE FUNCTION dbo.FACTOR(@origen VARCHAR(50), @destino VARCHAR(50), @clave VARCHAR(50))
RETURNS FLOAT
AS
BEGIN
    RETURN 1.0;
END;
GO

-- Trigger TEST-ONLY para provocar rollback determinista tras un write previo.
IF OBJECT_ID('dbo.TR_PartidasRollbackTest', 'TR') IS NOT NULL DROP TRIGGER dbo.TR_PartidasRollbackTest;
GO
CREATE TRIGGER dbo.TR_PartidasRollbackTest ON dbo.PARTIDAS AFTER INSERT
AS
BEGIN
    IF EXISTS (SELECT 1 FROM inserted WHERE CLAVE = 'ROLLBACK-X')
        THROW 51999, 'ROLLBACK_TEST_FORZADO', 1;
END;
GO
