-- =====================================================================
-- SOURCE           = LIVE OBJECT_DEFINITION
-- AUDITED_AT       = 2026-10-05
-- LEGACY_EXECUTION_SAFE = YES (verificado en Testcontainers)
-- =====================================================================
-- Copia textual fiel de CALE_IMMEX.dbo.CARGAACTAS (READ-ONLY).
-- Prohibido idealizar columnas, tipos, nombres, ordering o MAX()+1.
USE [CALE_IMMEX];
GO
CREATE PROCEDURE [dbo].[CARGAACTAS]
AS
BEGIN

DECLARE
@FOLIO VARCHAR(50),
@FECHA DATETIME,
@CLAVE VARCHAR(50),
@LINEA INTEGER,
@CANTIDAD FLOAT,
@UMC VARCHAR(50),
@DESCARGADIRIGIDA VARCHAR(50),
@SALIDAKEY BIGINT,
@PSALIDAKEY BIGINT,
@DESCRIPCION VARCHAR(250),
@UNIDAD VARCHAR(50),
@FRACCION VARCHAR(50),
@DIRIGIDOKEY BIGINT,
@VALORCOMERCIAL NUMERIC(18,4)




DECLARE ACTA CURSOR FAST_FORWARD FOR
    SELECT
       ACTA.FOLIO,
       ACTA.FECHA,
       ACTA.CLAVE,
       ACTA.LINEA,
       ACTA.CANTIDAD,
       ACTA.UMC,
       ACTA.DESCARGADIRIGIDA,
       ACTA.VALORCOMERCIAL
    FROM DBO.ACTA
    ORDER BY FOLIO






DELETE FROM GENERADORES
WHERE
TABLA = 'ACTA'


--DELETE FROM ERRORACTA

OPEN ACTA



FETCH NEXT FROM ACTA
INTO
 @FOLIO ,
 @FECHA ,
 @CLAVE ,
 @LINEA ,
 @CANTIDAD ,
 @UMC ,
 @DESCARGADIRIGIDA ,
 @VALORCOMERCIAL

WHILE @@FETCH_STATUS = 0
BEGIN

--PRINT @FOLIO


SELECT @SALIDAKEY = ISNULL(
(SELECT SALIDAS.SALIDAKEY FROM SALIDAS WHERE SALIDAS.DOCUMENTO = @FOLIO
 AND SALIDAS.TIPO_OPERACION = 'DESPERDICIOS'
 ),0)

PRINT @SALIDAKEY

IF @SALIDAKEY = 0
BEGIN

SELECT @SALIDAKEY = (SELECT ISNULL(MAX(SALIDAKEY),0) + 1 FROM SALIDAS)

INSERT INTO SALIDAS
(SALIDAKEY, DOCUMENTO ,FECHA ,TIPO_OPERACION,CVE_PEDIMENTO, CVE_CLIENTE,
ADUANA ,AGENTE , PAIS , TC, BLOQUEADO
 )
VALUES
(@SALIDAKEY,@FOLIO,@FECHA,'DESPERDICIOS','DESP','-','-','-','-',0,0)

END

-- INSERTA LOS NUMEROS DE PARTE

SELECT @PSALIDAKEY = ISNULL((SELECT PSALIDAKEY FROM SALIDAS
INNER JOIN PSALIDAS ON (SALIDAS.SALIDAKEY = PSALIDAS.SALIDALINK)
WHERE SALIDAS.DOCUMENTO = @FOLIO AND PSALIDAS.PARTIDA = @LINEA
),0)



IF @PSALIDAKEY = 0
BEGIN

  SELECT @PSALIDAKEY = (SELECT ISNULL(MAX(PSALIDAKEY),0) + 1 FROM PSALIDAS)

  SELECT @DESCRIPCION = (SELECT MATERIAL.DESCRIPCION FROM MATERIAL WHERE
  MATERIAL.CLAVE = @CLAVE)

  SELECT @FRACCION = (SELECT MATERIAL.FRACCION FROM MATERIAL WHERE
  MATERIAL.CLAVE = @CLAVE)

  SELECT @UNIDAD = (SELECT MATERIAL.UNIDAD FROM MATERIAL WHERE
  MATERIAL.CLAVE = @CLAVE)

  --Agrego en el caso de que se carguen productos

  IF ISNULL(@DESCRIPCION,'')=''
  BEGIN
  SELECT @DESCRIPCION = (SELECT PRODUCTOS.NOMBRE FROM PRODUCTOS WHERE
  PRODUCTOS.CVE_PRODUCTO = @CLAVE)
  END

  IF ISNULL(@FRACCION,'')=''
  BEGIN
  SELECT @FRACCION = (SELECT PRODUCTOS.FRACCION FROM PRODUCTOS WHERE
  PRODUCTOS.CVE_PRODUCTO = @CLAVE)
  END

  IF ISNULL(@UNIDAD,'')=''
  BEGIN
  SELECT @UNIDAD = (SELECT PRODUCTOS.UNIDAD FROM PRODUCTOS WHERE
  PRODUCTOS.CVE_PRODUCTO = @CLAVE)
  END

  INSERT INTO PSALIDAS
  (PSALIDAKEY , CLAVE ,DESCRIPCION , CANTIDAD , FRACCION , UNIDAD , SALIDALINK , PARTIDA, DESCARGADIRIGIDA, FECHA ,VAL_PESOS)
  VALUES
  (@PSALIDAKEY,@CLAVE, @DESCRIPCION, @CANTIDAD , @FRACCION , @UNIDAD, @SALIDAKEY , @LINEA , @DESCARGADIRIGIDA, @FECHA, @VALORCOMERCIAL)


END

FETCH NEXT FROM ACTA
INTO
 @FOLIO ,
 @FECHA ,
 @CLAVE ,
 @LINEA ,
 @CANTIDAD ,
 @UMC ,
 @DESCARGADIRIGIDA ,
 @VALORCOMERCIAL

END

CLOSE ACTA
DEALLOCATE ACTA

SELECT @DIRIGIDOKEY = ISNULL((SELECT MAX(DIRIGIDOKEY) FROM DIRIGIDO),0)+1

INSERT INTO DIRIGIDO
(DIRIGIDOKEY,DOCUMENTO,CLAVE,INCORPORADO,DESPERDICIO,MERMA,SALIDAKEY, PSALIDAKEY)
SELECT
ROW_NUMBER() OVER(ORDER BY PSALIDAKEY) + @DIRIGIDOKEY ,
DESCARGADIRIGIDA,CLAVE,CANTIDAD,0,0,SALIDALINK,PSALIDAKEY

FROM
PSALIDAS
WHERE
DESCARGADIRIGIDA <> '' AND PSALIDAKEY NOT IN
(SELECT DISTINCT PSALIDAKEY FROM DIRIGIDO)


END
GO
