CREATE PROC [dbo].[CARGA_MATERIALES] AS

DELETE FROM ECARGAMATERIAL
-- PRIMERO REVISO LAS UNIDADES DE MEDIDA

UPDATE DBO.CARGAMATERIAL
SET TIPOM = 'IMPORTADO'
WHERE ISNULL(TIPOM,'') <> 'NACIONAL'

UPDATE DBO.CARGAMATERIAL
SET FRACCION = '00000000'
WHERE TIPOM = 'NACIONAL'


INSERT INTO DBO.ECARGAMATERIAL
(CARGAMATERIALKEY,ERROR)
SELECT CARGAMATERIALKEY, 'LA UNIDAD COMERCIAL NO ESTA EN EL CATALOGO DE UNIDADES'  FROM DBO.CARGAMATERIAL
WHERE
DBO.VALIDUNIT(UNIDADCOMERCIAL) NOT IN
(SELECT CVE_UNIDAD FROM UNIDAD)

INSERT INTO DBO.ECARGAMATERIAL
(CARGAMATERIALKEY,ERROR)
SELECT CARGAMATERIALKEY, 'LA UNIDAD TARIFA NO ESTA EN EL CATALOGO DE UNIDADES'  FROM DBO.CARGAMATERIAL
WHERE
DBO.VALIDUNIT(UNIDADTARIFA) NOT IN
(SELECT CVE_UNIDAD FROM UNIDAD)
AND TIPOM = 'IMPORTADO'

-- REVISA LA LONGITUD DE LA FRACCION
INSERT INTO DBO.ECARGAMATERIAL
(CARGAMATERIALKEY,ERROR)
SELECT CARGAMATERIALKEY, 'LA LONGITUD DE LA FRACCION ES INCORRECTA'  FROM DBO.CARGAMATERIAL
WHERE
LEN(FRACCION) <> 8

-- REVISA LA CLAVE TENGA AL MENOS 5 CARACTERS
INSERT INTO DBO.ECARGAMATERIAL
(CARGAMATERIALKEY,ERROR)
SELECT CARGAMATERIALKEY, 'LA LONGITUD DE LA CLAVE ES ERRONEA'  FROM DBO.CARGAMATERIAL
WHERE
LEN(CLAVEMATERIAL) < 5

-- REVISA LA CLAVE ALTERNATIVA SI EXISTE QUE SEA MAYOR A 5

INSERT INTO DBO.ECARGAMATERIAL
(CARGAMATERIALKEY,ERROR)
SELECT CARGAMATERIALKEY, 'LA LONGITUD DE LA CLAVE ES ERRONEA'  FROM DBO.CARGAMATERIAL
WHERE
LEN(CLAVEMATERIALPROVEEDOR) < 5 AND
ISNULL(CLAVEMATERIALPROVEEDOR,'') <> ''


-- REVISA QUE NO ESTEN DOBLES LOS CODIGOS.
INSERT INTO DBO.ECARGAMATERIAL
(CARGAMATERIALKEY,ERROR)

SELECT CARGAMATERIALKEY,'CLAVE REPETIDA MAS DE 1 VEZ' FROM DBO.CARGAMATERIAL WHERE
CLAVEMATERIAL IN
(
SELECT CLAVEMATERIAL FROM
(
SELECT COUNT(*) REPETICIONES,CLAVEMATERIAL FROM
DBO.CARGAMATERIAL
GROUP BY CLAVEMATERIAL
) XX
WHERE XX.REPETICIONES > 1
)

-- INSERTA LOS QUE NO TIENEN ERROR

DELETE FROM MATERIAL
WHERE CLAVE IN
(SELECT CLAVEMATERIAL FROM DBO.CARGAMATERIAL WHERE
CARGAMATERIALKEY NOT IN
(SELECT DISTINCT CARGAMATERIALKEY FROM DBO.ECARGAMATERIAL)
)

-- BORRA LOS FACTORES SIN MATERIA

DELETE FROM DBO.FACTORESMP
WHERE MATERIALKEY NOT IN
(SELECT MATERIALKEY FROM MATERIAL)

-- INSERTA LOS QUE ESTAN OK

DECLARE @MATERIALKEY AS BIGINT

SELECT @MATERIALKEY = ISNULL((SELECT MAX(MATERIALKEY) FROM MATERIAL),0) + 1

INSERT INTO [DBO].[MATERIAL]
           ([MATERIALKEY],[CLAVE],CLAVEPROVEEDOR,[DESCRIPCION],[FRACCION]
           ,[UNIDAD],[UNIDADT],[TIPOMATERIAL],[TIPO],[TIPOM]
           ,ALMACENKEY,[numero_serie],marca,modelo)
SELECT ROW_NUMBER() OVER(ORDER BY CLAVEMATERIAL) + @MATERIALKEY,
SUBSTRING(CLAVEMATERIAL,1,50) ,SUBSTRING(CLAVEMATERIALPROVEEDOR,1,40)
,SUBSTRING(DESCRIPCIONCOMERCIAL,1,250),FRACCION,
DBO.VALIDUNIT(UNIDADCOMERCIAL),DBO.VALIDUNIT(UNIDADTARIFA),'MATERIAS PRIMAS','MAT'
, TIPOM, DBO.ENTIDAD(DIVISION)
,[numeroserie],marca,modelo
FROM DBO.CARGAMATERIAL
WHERE
CARGAMATERIALKEY NOT IN
(SELECT DISTINCT CARGAMATERIALKEY FROM DBO.ECARGAMATERIAL)


--
-- COLOCAMOS LOS FACTORES
-- KG
INSERT INTO DBO.FACTORESMP
(FACTOR,UNIDAD,MATERIALKEY,UNIDADCONVERTIR,CLAVE)
SELECT KG , DBO.VALIDUNIT(UNIDADCOMERCIAL),
(SELECT TOP 1 MATERIALKEY FROM DBO.MATERIAL WHERE CLAVE = CLAVEMATERIAL) MATERIALKEY  ,
'KG',CLAVEMATERIAL
FROM DBO.CARGAMATERIAL
WHERE
ISNULL(KG,0) > 0 AND
CARGAMATERIALKEY NOT IN
(SELECT DISTINCT CARGAMATERIALKEY FROM DBO.ECARGAMATERIAL)

-- GR

INSERT INTO DBO.FACTORESMP
(FACTOR,UNIDAD,MATERIALKEY,UNIDADCONVERTIR,CLAVE)
SELECT GR , DBO.VALIDUNIT(UNIDADCOMERCIAL),
(SELECT TOP 1 MATERIALKEY FROM DBO.MATERIAL WHERE CLAVE = CLAVEMATERIAL) MATERIALKEY  ,
'GR',CLAVEMATERIAL
FROM DBO.CARGAMATERIAL
WHERE
ISNULL(GR,0) > 0 AND
CARGAMATERIALKEY NOT IN
(SELECT DISTINCT CARGAMATERIALKEY FROM DBO.ECARGAMATERIAL)


-- ML

INSERT INTO DBO.FACTORESMP
(FACTOR,UNIDAD,MATERIALKEY,UNIDADCONVERTIR,CLAVE)
SELECT ML , DBO.VALIDUNIT(UNIDADCOMERCIAL),
(SELECT TOP 1 MATERIALKEY FROM DBO.MATERIAL WHERE CLAVE = CLAVEMATERIAL) MATERIALKEY  ,
'ML',CLAVEMATERIAL
FROM DBO.CARGAMATERIAL
WHERE
ISNULL(ML,0) > 0 AND
CARGAMATERIALKEY NOT IN
(SELECT DISTINCT CARGAMATERIALKEY FROM DBO.ECARGAMATERIAL)


-- MCUA

INSERT INTO DBO.FACTORESMP
(FACTOR,UNIDAD,MATERIALKEY,UNIDADCONVERTIR,CLAVE)
SELECT MCUA , DBO.VALIDUNIT(UNIDADCOMERCIAL),
(SELECT TOP 1 MATERIALKEY FROM DBO.MATERIAL WHERE CLAVE = CLAVEMATERIAL) MATERIALKEY  ,
'MCUA',CLAVEMATERIAL
FROM DBO.CARGAMATERIAL
WHERE
ISNULL(MCUA,0) > 0 AND
CARGAMATERIALKEY NOT IN
(SELECT DISTINCT CARGAMATERIALKEY FROM DBO.ECARGAMATERIAL)


-- MCUB

INSERT INTO DBO.FACTORESMP
(FACTOR,UNIDAD,MATERIALKEY,UNIDADCONVERTIR,CLAVE)
SELECT MCUB , DBO.VALIDUNIT(UNIDADCOMERCIAL),
(SELECT TOP 1 MATERIALKEY FROM DBO.MATERIAL WHERE CLAVE = CLAVEMATERIAL) MATERIALKEY  ,
'MCUB',CLAVEMATERIAL
FROM DBO.CARGAMATERIAL
WHERE
ISNULL(MCUB,0) > 0 AND
CARGAMATERIALKEY NOT IN
(SELECT DISTINCT CARGAMATERIALKEY FROM DBO.ECARGAMATERIAL)



-- PZA

INSERT INTO DBO.FACTORESMP
(FACTOR,UNIDAD,MATERIALKEY,UNIDADCONVERTIR,CLAVE)
SELECT PZA , DBO.VALIDUNIT(UNIDADCOMERCIAL),
(SELECT TOP 1 MATERIALKEY FROM DBO.MATERIAL WHERE CLAVE = CLAVEMATERIAL) MATERIALKEY  ,
'PZA',CLAVEMATERIAL
FROM DBO.CARGAMATERIAL
WHERE
ISNULL(PZA,0) > 0 AND
CARGAMATERIALKEY NOT IN
(SELECT DISTINCT CARGAMATERIALKEY FROM DBO.ECARGAMATERIAL)


-- LT

INSERT INTO DBO.FACTORESMP
(FACTOR,UNIDAD,MATERIALKEY,UNIDADCONVERTIR,CLAVE)
SELECT LT , DBO.VALIDUNIT(UNIDADCOMERCIAL),
(SELECT TOP 1 MATERIALKEY FROM DBO.MATERIAL WHERE CLAVE = CLAVEMATERIAL) MATERIALKEY  ,
'LT',CLAVEMATERIAL
FROM DBO.CARGAMATERIAL
WHERE
ISNULL(LT,0) > 0 AND
CARGAMATERIALKEY NOT IN
(SELECT DISTINCT CARGAMATERIALKEY FROM DBO.ECARGAMATERIAL)


-- PAR

INSERT INTO DBO.FACTORESMP
(FACTOR,UNIDAD,MATERIALKEY,UNIDADCONVERTIR,CLAVE)
SELECT PAR , DBO.VALIDUNIT(UNIDADCOMERCIAL),
(SELECT TOP 1 MATERIALKEY FROM DBO.MATERIAL WHERE CLAVE = CLAVEMATERIAL) MATERIALKEY  ,
'PAR',CLAVEMATERIAL
FROM DBO.CARGAMATERIAL
WHERE
ISNULL(PAR,0) > 0 AND
CARGAMATERIALKEY NOT IN
(SELECT DISTINCT CARGAMATERIALKEY FROM DBO.ECARGAMATERIAL)


-- MI

INSERT INTO DBO.FACTORESMP
(FACTOR,UNIDAD,MATERIALKEY,UNIDADCONVERTIR,CLAVE)
SELECT MI , DBO.VALIDUNIT(UNIDADCOMERCIAL),
(SELECT TOP 1 MATERIALKEY FROM DBO.MATERIAL WHERE CLAVE = CLAVEMATERIAL) MATERIALKEY  ,
'MI',CLAVEMATERIAL
FROM DBO.CARGAMATERIAL
WHERE
ISNULL(MI,0) > 0 AND
CARGAMATERIALKEY NOT IN
(SELECT DISTINCT CARGAMATERIALKEY FROM DBO.ECARGAMATERIAL)


-- JGO

INSERT INTO DBO.FACTORESMP
(FACTOR,UNIDAD,MATERIALKEY,UNIDADCONVERTIR,CLAVE)
SELECT JGO , DBO.VALIDUNIT(UNIDADCOMERCIAL),
(SELECT TOP 1 MATERIALKEY FROM DBO.MATERIAL WHERE CLAVE = CLAVEMATERIAL) MATERIALKEY  ,
'JGO',CLAVEMATERIAL
FROM DBO.CARGAMATERIAL
WHERE
ISNULL(JGO,0) > 0 AND
CARGAMATERIALKEY NOT IN
(SELECT DISTINCT CARGAMATERIALKEY FROM DBO.ECARGAMATERIAL)


-- TON

INSERT INTO DBO.FACTORESMP
(FACTOR,UNIDAD,MATERIALKEY,UNIDADCONVERTIR,CLAVE)
SELECT TON , DBO.VALIDUNIT(UNIDADCOMERCIAL),
(SELECT TOP 1 MATERIALKEY FROM DBO.MATERIAL WHERE CLAVE = CLAVEMATERIAL) MATERIALKEY  ,
'TON',CLAVEMATERIAL
FROM DBO.CARGAMATERIAL
WHERE
ISNULL(TON,0) > 0 AND
CARGAMATERIALKEY NOT IN
(SELECT DISTINCT CARGAMATERIALKEY FROM DBO.ECARGAMATERIAL)

-- BAR

INSERT INTO DBO.FACTORESMP
(FACTOR,UNIDAD,MATERIALKEY,UNIDADCONVERTIR,CLAVE)
SELECT BAR , DBO.VALIDUNIT(UNIDADCOMERCIAL),
(SELECT TOP 1 MATERIALKEY FROM DBO.MATERIAL WHERE CLAVE = CLAVEMATERIAL) MATERIALKEY  ,
'BAR',CLAVEMATERIAL
FROM DBO.CARGAMATERIAL
WHERE
ISNULL(BAR,0) > 0 AND
CARGAMATERIALKEY NOT IN
(SELECT DISTINCT CARGAMATERIALKEY FROM DBO.ECARGAMATERIAL)

-- GRN

INSERT INTO DBO.FACTORESMP
(FACTOR,UNIDAD,MATERIALKEY,UNIDADCONVERTIR,CLAVE)
SELECT GRN , DBO.VALIDUNIT(UNIDADCOMERCIAL),
(SELECT TOP 1 MATERIALKEY FROM DBO.MATERIAL WHERE CLAVE = CLAVEMATERIAL) MATERIALKEY  ,
'GRN',CLAVEMATERIAL
FROM DBO.CARGAMATERIAL
WHERE
ISNULL(GRN,0) > 0 AND
CARGAMATERIALKEY NOT IN
(SELECT DISTINCT CARGAMATERIALKEY FROM DBO.ECARGAMATERIAL)

-- DECE

INSERT INTO DBO.FACTORESMP
(FACTOR,UNIDAD,MATERIALKEY,UNIDADCONVERTIR,CLAVE)
SELECT DECE , DBO.VALIDUNIT(UNIDADCOMERCIAL),
(SELECT TOP 1 MATERIALKEY FROM DBO.MATERIAL WHERE CLAVE = CLAVEMATERIAL) MATERIALKEY  ,
'DECE',CLAVEMATERIAL
FROM DBO.CARGAMATERIAL
WHERE
ISNULL(DECE,0) > 0 AND
CARGAMATERIALKEY NOT IN
(SELECT DISTINCT CARGAMATERIALKEY FROM DBO.ECARGAMATERIAL)

-- CIEN

INSERT INTO DBO.FACTORESMP
(FACTOR,UNIDAD,MATERIALKEY,UNIDADCONVERTIR,CLAVE)
SELECT CIEN , DBO.VALIDUNIT(UNIDADCOMERCIAL),
(SELECT TOP 1 MATERIALKEY FROM DBO.MATERIAL WHERE CLAVE = CLAVEMATERIAL) MATERIALKEY  ,
'CIEN',CLAVEMATERIAL
FROM DBO.CARGAMATERIAL
WHERE
ISNULL(CIEN,0) > 0 AND
CARGAMATERIALKEY NOT IN
(SELECT DISTINCT CARGAMATERIALKEY FROM DBO.ECARGAMATERIAL)



-- GR

INSERT INTO DBO.FACTORESMP
(FACTOR,UNIDAD,MATERIALKEY,UNIDADCONVERTIR,CLAVE)
SELECT DOCE , DBO.VALIDUNIT(UNIDADCOMERCIAL),
(SELECT TOP 1 MATERIALKEY FROM DBO.MATERIAL WHERE CLAVE = CLAVEMATERIAL) MATERIALKEY  ,
'DOCE',CLAVEMATERIAL
FROM DBO.CARGAMATERIAL
WHERE
ISNULL(DOCE,0) > 0 AND
CARGAMATERIALKEY NOT IN
(SELECT DISTINCT CARGAMATERIALKEY FROM DBO.ECARGAMATERIAL)


-- BOTELLA

INSERT INTO DBO.FACTORESMP
(FACTOR,UNIDAD,MATERIALKEY,UNIDADCONVERTIR,CLAVE)
SELECT CAJA , DBO.VALIDUNIT(UNIDADCOMERCIAL),
(SELECT TOP 1 MATERIALKEY FROM DBO.MATERIAL WHERE CLAVE = CLAVEMATERIAL) MATERIALKEY  ,
'CAJA',CLAVEMATERIAL
FROM DBO.CARGAMATERIAL
WHERE
ISNULL(CAJA,0) > 0 AND
CARGAMATERIALKEY NOT IN
(SELECT DISTINCT CARGAMATERIALKEY FROM DBO.ECARGAMATERIAL)


-- GR

INSERT INTO DBO.FACTORESMP
(FACTOR,UNIDAD,MATERIALKEY,UNIDADCONVERTIR,CLAVE)
SELECT CAJA , DBO.VALIDUNIT(UNIDADCOMERCIAL),
(SELECT TOP 1 MATERIALKEY FROM DBO.MATERIAL WHERE CLAVE = CLAVEMATERIAL) MATERIALKEY  ,
'CAJA',CLAVEMATERIAL
FROM DBO.CARGAMATERIAL
WHERE
ISNULL(CAJA,0) > 0 AND
CARGAMATERIALKEY NOT IN
(SELECT DISTINCT CARGAMATERIALKEY FROM DBO.ECARGAMATERIAL)


-- GR

INSERT INTO DBO.FACTORESMP
(FACTOR,UNIDAD,MATERIALKEY,UNIDADCONVERTIR,CLAVE)
SELECT BOTELLA , DBO.VALIDUNIT(UNIDADCOMERCIAL),
(SELECT TOP 1 MATERIALKEY FROM DBO.MATERIAL WHERE CLAVE = CLAVEMATERIAL) MATERIALKEY  ,
'BOTELLA',CLAVEMATERIAL
FROM DBO.CARGAMATERIAL
WHERE
ISNULL(BOTELLA,0) > 0 AND
CARGAMATERIALKEY NOT IN
(SELECT DISTINCT CARGAMATERIALKEY FROM DBO.ECARGAMATERIAL)
